- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g @angular/cli'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'src/'
- task: CmdLine@2
  inputs:
    script: 'npm run build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'